spring:
  datasource:
    url: jdbc:mysql://ocr.huaweicloud.com:3316/springtest?useSSL=false&serverTimezone=UTC
    username: mysql
    #password: 123456
    password: huawei@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.login.demo.entity
  mapper-locations: classpath:com.login.demo.mapper/*.xml

server:
  #端口号
  port: 9091

redis:
  host: ocr.huaweicloud.com
  port: 6389
telnet:
  host: ocr.huaweicloud.com
  port:23

